-- Core/MediaPack.lua : bundled bar textures + fonts so Custodian ships a full media library
-- with NO required addons. The files under Media\statusbar\ and Media\fonts\ are copies of the
-- SharedMedia / SharedMediaAdditionalFonts packs; here they're registered into LibSharedMedia by
-- the SAME NAMES those addons use. LSM:Register is FIRST-WINS, so when SharedMedia is also
-- installed the duplicate registrations are simply ignored (one list entry, no collision); when
-- it isn't, Custodian provides them itself. Generated from the source packs — edit there + re-gen.

local LSM = LibStub and LibStub("LibSharedMedia-3.0", true)
if not LSM then return end

local BAR  = "Interface\\AddOns\\Custodian\\Media\\statusbar\\"   -- textures: registered without extension (WoW resolves .tga)
local FONT = "Interface\\AddOns\\Custodian\\Media\\fonts\\"

local BARS = {
  { "Aluminium", "Aluminium" },
  { "Armory", "Armory" },
  { "BantoBar", "BantoBar" },
  { "Bars", "Bars" },
  { "Bumps", "Bumps" },
  { "Button", "Button" },
  { "Charcoal", "Charcoal" },
  { "Cilo", "Cilo" },
  { "Cloud", "Cloud" },
  { "Comet", "Comet" },
  { "Dabs", "Dabs" },
  { "DarkBottom", "DarkBottom" },
  { "Diagonal", "Diagonal" },
  { "Empty", "Empty" },
  { "Falumn", "Falumn" },
  { "Fifths", "Fifths" },
  { "Flat", "Flat" },
  { "Fourths", "Fourths" },
  { "Frost", "Frost" },
  { "Glamour", "Glamour" },
  { "Glamour2", "Glamour2" },
  { "Glamour3", "Glamour3" },
  { "Glamour4", "Glamour4" },
  { "Glamour5", "Glamour5" },
  { "Glamour6", "Glamour6" },
  { "Glamour7", "Glamour7" },
  { "Glass", "Glass" },
  { "Glaze", "Glaze" },
  { "Glaze v2", "Glaze2" },
  { "Gloss", "Gloss" },
  { "Graphite", "Graphite" },
  { "Grid", "Grid" },
  { "Hatched", "Hatched" },
  { "Healbot", "Healbot" },
  { "Lyfe", "Lyfe" },
  { "LiteStep", "LiteStep" },
  { "LiteStepLite", "LiteStepLite" },
  { "Melli", "Melli" },
  { "Melli Dark", "MelliDark" },
  { "Melli Dark Rough", "MelliDarkRough" },
  { "Minimalist", "Minimalist" },
  { "Otravi", "Otravi" },
  { "Outline", "Outline" },
  { "Perl", "Perl" },
  { "Perl v2", "Perl2" },
  { "Pill", "Pill" },
  { "Rain", "Rain" },
  { "Rocks", "Rocks" },
  { "Round", "Round" },
  { "Ruben", "Ruben" },
  { "Runes", "Runes" },
  { "Skewed", "Skewed" },
  { "Smooth", "Smooth" },
  { "Smooth v2", "Smoothv2" },
  { "Smudge", "Smudge" },
  { "Steel", "Steel" },
  { "Striped", "Striped" },
  { "Tube", "Tube" },
  { "Water", "Water" },
  { "Wglass", "Wglass" },
  { "Wisps", "Wisps" },
  { "Xeon", "Xeon" },
}

local FONTS = {
  { "Accidental Presidency", "Accidental Presidency.ttf" },
  { "ACTION MAN", "ActionMan.ttf" },
  { "Alba Super", "ALBAS___.ttf" },
  { "Anonymous Pro", "AnonymousPro-Regular.ttf" },
  { "Arm Wrestler", "ArmWrestler.ttf" },
  { "Atkinson Hyperlegible Next", "AtkinsonHyperlegibleNext-Regular.ttf" },
  { "AvantGarde LT Book", "AvantGarde_LT_Book_Regular.ttf" },
  { "Baar Sophia", "BAARS___.TTF" },
  { "Bazooka", "Bazooka.ttf" },
  { "Blazed", "Blazed.ttf" },
  { "Boris Black Bloxx", "BorisBlackBloxx.ttf" },
  { "Boris Black Bloxx Dirty", "BorisBlackBloxxDirty.ttf" },
  { "Cabin", "Cabin-Regular.ttf" },
  { "Celestia Redux", "CelestiaMediumRedux1.55.ttf" },
  { "Century Gothic", "centurygothic.ttf" },
  { "Collegiate", "COLLEGIA.ttf" },
  { "Continuum Medium", "ContinuumMedium.ttf" },
  { "Cooline, Bold Italic", "coolinbi.ttf" },
  { "DejaVu Sans", "DejaVuSans.ttf" },
  { "DejaVu Sans, Bold", "DejaVuSans-Bold.ttf" },
  { "DieDieDie", "DieDieDie.ttf" },
  { "Diogenes", "DIOGENES.ttf" },
  { "Disko", "Disko.ttf" },
  { "Expressway, Regular", "expressway rg.otf" },
  { "Expressway, Bold", "Expressway-Bold.ttf" },
  { "Frakturika Spamless", "FRAKS___.ttf" },
  { "Gotham Narrow Ultra", "GothamNarrow-Ultra.ttf" },
  { "Homespun TT BRK", "Homespun.ttf" },
  { "Impact", "impact.ttf" },
  { "JetBrains Mono", "JetBrainsMono-Regular.ttf" },
  { "Liberation Sans", "LiberationSans-Regular.ttf" },
  { "Liberation Serif", "LiberationSerif-Regular.ttf" },
  { "Mystic Orbs", "MystikOrbs.ttf" },
  { "NanumGothic", "NanumGothic-Regular.ttf" },
  { "Nunito", "Nunito-Regular.ttf" },
  { "OpenDyslexic 3", "OpenDyslexic3-Regular.ttf" },
  { "Pokemon Solid", "Pokemon Solid.ttf" },
  { "Prototype", "Prototype.ttf" },
  { "PT Sans Narrow, Bold", "PTSansNarrow-Bold.ttf" },
  { "Rock Show Whiplash", "Rock Show Whiplash.ttf" },
  { "SF Diego Sans", "SF Diego Sans.ttf" },
  { "Solange", "Solange.ttf" },
  { "Star Cine", "starcine.ttf" },
  { "Trashco", "trashco.ttf" },
  { "Ubuntu Condensed", "Ubuntu-C.ttf" },
  { "Ubuntu Light", "Ubuntu-L.ttf" },
  { "Waltograph UI", "waltographUI.ttf" },
  { "Verdana", "Verdana.ttf" },
  { "X360", "X360.ttf" },
  { "Yanone Kaffeesatz Regular", "YanoneKaffeesatz-Regular.ttf" },
}

for _, e in ipairs(BARS)  do LSM:Register("statusbar", e[1], BAR  .. e[2]) end
for _, e in ipairs(FONTS) do LSM:Register("font",      e[1], FONT .. e[2]) end
